### ISSUE TITLE
Loading dynamic sections of the app shell while using a service worker.

### ISSUE THREAD

**Issue by jorgecuevas92** [rossta/serviceworker-rails#10]
I am trying to render dynamically the user icon depending if the user is logged or not.

It is a simple if else depending on the session[:user_id] content.

The problem is that whenever I successfully log in to the app, the service worker takes over the fetch and shows the button that leads to the log in modal again.

I tried using an ajax request to render the correct content after the service worker has done its part loading the app shell, but I have not been successful doing so .

Has anyone found a way to accomplish this?

**Comment by rossta** [comment]
Thanks for your question. From what you've described, you may be better off asking this on StackOverflow unless you have an issue specific to the `serviceworker-rails` gem. You will probably also need to show your ServiceWorker code (at least) to get the help you're looking for.

**Comment by jorgecuevas92** [comment]
You are right, this was not the place to post this, anyway, thanks for your response, your gem has been extremely helpful.
