### ISSUE TITLE
SystemStackError

### ISSUE THREAD

**Issue by mdi** [rossta/serviceworker-rails#21]
Trying this out, and after removing the comments in serviceworker.js.erb, I get the following error when trying to load any page.

```
SystemStackError (stack level too deep):
  
app/assets/javascripts/serviceworker.js.erb:6:in `_evaluate_template'
```

**Comment by rossta** [comment]
What is in your `serviceworker.js.erb`? Are you including it `application.js`?

**Comment by mdi** [comment]
That was it. Thanks!

**Comment by domchristie** [comment]
Great library!
Just a quick note on this. Unfortunately using: 

```js
//= require_tree ./
//= stub serviceworker
```

does not help prevent this issue.
