### ISSUE TITLE
Should serviceworker:install  set up default offline behavior

### ISSUE THREAD

**Issue by seanpaulkelley** [rossta/serviceworker-rails#27]
Should the install provide basic offline page functionality?

I used rails g serviceworker:install 
When I turn off network the /public/offline.html page is not displayed.

In the 'Test the Setup' section of your readme you say:
The application JavaScript and CSS assets are added to the browser's request/response Cache.

I am not sure how to verify the caching for sure.  Please see screenshot of where I think I should see it
![screenshot from 2017-01-24 16-35-55](https://cloud.githubusercontent.com/assets/8125357/22268205/a86561e4-e254-11e6-9957-ee092b90340a.png)

**Comment by rossta** [comment]
Thanks for the report. Do you see any console errors when you're offline?

**Comment by seanpaulkelley** [comment]
yes- here they are
![offline errors-pwa](https://cloud.githubusercontent.com/assets/8125357/22335021/f7efe99e-e3aa-11e6-9a5e-309e65b190a2.png)

**Comment by rossta** [comment]
Thanks... could be a regression. I may not be able to look into this right away, so PRs are welcome in the mean time.

**Comment by rossta** [comment]
@seanpaulkelley I believe I have a fix for this. If you'd like to help me test the branch with bug fix, here are recommended steps:

1. Check out a branch for your Rails app to test regenerating the serviceworker.
2. Modify your `Gemfile` to point to the branch with the bug fix: `gem 'serviceworker-rails', github: 'rossta/serviceworker-rails', branch: 'bug_fix_serviceworker_activation_cache_delete'`
3. Run `$ bundle update`
4. Run `$ rails g serviceworker:install`. Select `Y` if generator asks you to overwrite `serviceworker.js.erb`.
5. Restart your app and load in Chrome.
6. Unregister the serviceworker in DevTools > Application > Service Workers (diagram)
![developer_tools_-_http___localhost_3004__and_you_are_not_connected_to_the_internet](https://cloud.githubusercontent.com/assets/11673/22483000/69bb1b58-e7c9-11e6-9fa2-c52cc8773006.jpg)
7. Reload the app online to re-register the new serviceworker
8. Reload the app offline to test the offline page

Let me know whether that works for you.

**Comment by seanpaulkelley** [comment]
that seems to cache fine-- thanks!

**Comment by rossta** [comment]
@seanpaulkelley Merged and released new version `0.5.4`. Thanks!
