### ISSUE TITLE
offline page provided when not offline

### ISSUE THREAD

**Issue by seanpaulkelley** [rossta/serviceworker-rails#33]
I have a couple of situtations where the offline page is getting displayed when the user is not offline.  First situtation is logging in with facebook using omniauth-facebook gem.  I login, get the offline page, then have to reload.  I then get my page and I am logged in.

The the other time I see it is when I run a scheduling process which take a list of events then orders them.  If I schedule a list of events with just 2 I don't get the offline page but if I schedule and list of 30 events I see offline page.  

I am not sure how to be more helpful as I do not get meaningful errors.  I suspect that its' a matter of how long it takes to get response from network (I am running my production on heroku).

Here is a copy of my browser log when attempting to login in with facebook which I don't thin is helpful:

[Companion] Service worker registered!
Fetch API cannot load https://www.facebook.com/v2.6/dialog/oauth?client_id=xxxxxxxxx&redir…pe=code&scope=email&state=757575745875873857857435775843. Redirect from 'https://www.facebook.com/v2.6/dialog/oauth?client_id=xxxxxxxxx&redir…pe=code&scope=email&state=32758475758742574385 to 'https://app.antaresdressage.com/users/auth/facebook/callback?code=ggjdhghgjdfghdgs…Uu33atafgyCLAYQ&state=fhgkjl7676g78g7d6g76dsg7fds6g7f6g5e4979760490704#_=_' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mysite.com' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
serviceworker.js:1 [Serviceworker] Fetchin
g offline content FetchEvent {request: Request, clientId: "djfhggf766g76fd7g6fd7g6-c311-42b3-9e3d-09e5aa1fb2ad", isReload: false, type: "fetch", target: ServiceWorkerGlobalScope…}

**Comment by seanpaulkelley** [comment]
sorry- did not see that you had updated gem (although not release).  I grabbed the master and it seems to resolve the issue so I will close for now at least with regard to fb login

**Comment by rossta** [comment]
Thanks for the report. 

I can't be sure whether the updates on master actually resolved your problem or not, but generally speaking, the generated serviceworker script may not be adequate to cover your use case. It's meant to be a starting point for displaying an offline page when fetch fails, but that might not be what you want for all requests. It would be up to you to modify the fetch callback to deal with failures that might occur during a cross-origin request or perhaps only invoke the offline callback if the failure occurs for certain hosts, like your own.
