### ISSUE TITLE
Not working on staging or production

### ISSUE THREAD

**Issue by nmilenkovic** [rossta/serviceworker-rails#35]
- I'm using https,
- My serviceworker file  has path /assets/serviceworker-465b73bc03f124ef4858b94090f29be3.js (MD5) and it's served by CDN but also is available in host site.
- I'm doing precompiling of serviceworker file
- I have  `match "/serviceworker.js"` in serviceworker.rb

Everything is ok on localhost, but when I've deploy app on staging it's not working. 
I can get sw if i look it on path i already wrote up, but it's not available on path /serviceworker.js.

Any suggestion?

**Comment by rossta** [comment]
Thanks for the report. What is the value of `Rails.application.config.compile` in your staging/production environments?

**Comment by nmilenkovic** [comment]
Versions: 
- rails (4.1.15)
- sprockets (2.12.4)
- sprockets-rails (2.3.3)

And config.assets.compile = false

Thanks for response.

**Comment by rossta** [comment]
I'm not able to reproduce with those versions. Here's a sample app I just launched:

Repo: https://bitbucket.org/rossta/serviceworker_sample_rails41
App: https://thawing-journey-34177.herokuapp.com

You can try inspecting the app configuration in my repo to see if there are any obvious differences.

Another thing to try: could you run `RAILS_ENV=production rake middleware` and verify the output includes `use ServiceWorker::Middleware`?

**Comment by nmilenkovic** [comment]
I don't have access to that bitbucket repo

**Comment by rossta** [comment]
It's public now.

**Comment by rossta** [comment]
If you're able to open up a rails console in your staging or production environment, could you show return values for the following?

```
Rails.application.config.compile # => ?
code, headers, body = Rails.application.assets.call 'PATH_INFO' => '/serviceworker.js' # => ?
code # =>
headers # =>
body.to_s # => ?
```

Replace `/serviceworker.js` with wherever you've mounted your serviceworker script if different.

**Comment by lyonsv** [comment]
Rails.application.config.assets.compile  => false
Rails.application.assets is nil -> I'm looking into why at the moment.

**Comment by rossta** [comment]
If you get a chance, try this instead:

```ruby
asset_path = ::ActionController::Base.helpers.asset_path('/serviceworker.js') # => ?
code, headers, body = ::Rack::File.new(::Rails.public_path).call 'PATH_INFO' => asset_path
code # => ?
headers # => ?
body.to_s # => ?
```

**Comment by lyonsv** [comment]
code - 405
headers  - {"Content-Type"=>"text/plain", "Content-Length"=>"19", "X-Cascade"=>"pass", "Allow"=>"GET, HEAD, OPTIONS"}
body - ["Method Not Allowed\n"]

**Comment by rossta** [comment]
@lyonsv Thanks, I think I understand the issue for you now. Working on a fix.

@nmilenkovic Do you also use a CDN or otherwise configure `config.action_controller.asset_host` in your production/staging environments?

**Comment by nmilenkovic** [comment]
I'm also using CDN.

**Comment by lyonsv** [comment]
Your latest PR seems to solve that issue for me - thanks @rossta

**Comment by rossta** [comment]
Awesome, great to hear @lyonsv . Your info helped me figure out the issue. I'll merge and release a new version soon.

**Comment by rossta** [comment]
You can now upgrade to `0.5.5` to resolve this issue.

**Comment by nmilenkovic** [comment]
Your update also fixed my problem. Thanks @rossta  :)
