### ISSUE TITLE
Failures: Manifest start_url is not cached by a Service Worker.

### ISSUE THREAD

**Issue by eveevans** [rossta/serviceworker-rails#38]
Lighthouse is requesting the service worker to cache the start_url defined on Manifest. But the default serviceworker.js and the serviceworker-rails documentation doesn't contemplate this. 

I'm not sure if this is the standar, but Lighthouse starting to do this in its last version. 
(here is the change https://github.com/GoogleChrome/lighthouse/pull/2040/files ). 

Is this really necessary in order to enable the install prompt ?

**Comment by rossta** [comment]
Thanks for sharing this question though I think this issue is outside the scope of this project. I'm not sure how the current Lighthouse rules align with mobile device behavior but it may be an indication of where things are headed.

**Comment by eveevans** [comment]
Well, the point is: if the serviceworker.js generated by default by the gem, should include a start_url

**Comment by neavilag** [comment]
I have the same issue from lighthouse with my PWA app.climadiario.com but actually my app prompt for installation on chrome for Android  is this a bug ?

Lighthouse says I failed and audit due to "Failures: Manifest start_url is not cached by a Service Worker."
