### ISSUE TITLE
Insert paths to 'function onInstall( )' dynamically - Ruby on Rails

### ISSUE THREAD

**Issue by PedroPauloML** [rossta/serviceworker-rails#39]
My necessity is add all path of the system to save in cache.
My system is dynamic, so I need add the paths of action show (/users/:id) on function 'onInstall' and update the version of cache. How do I do this of form dynamically?

**Comment by rossta** [comment]
Thanks for your question. This sounds like an interesting topic, but it would more appropriate for StackOverflow.
