### ISSUE TITLE
Can I use remote images as icons in manifest.json.erb ?

### ISSUE THREAD

**Issue by misner** [rossta/serviceworker-rails#40]
Is it possible to change local images into remote images ?

going from
{
      "src": "/assets/serviceworker-rails/heart-96x96.png",
      "sizes": "96x96",
      "type": "image/png"
    }

to

{
      "src": "http://cloudfront/example/heart-96x96.png",
      "sizes": "96x96",
      "type": "image/png"
    }

Would that affect performance or ability to use cache for service workers in your Gem ?

Thanks a lot for an awesome gem

**Comment by rossta** [comment]
Yes. If you have your asset host configured for CDN in production, you can use erb to interpolate the image page:

```json
"src": "<%= asset_path('example/heart.png') %>"
```

As for performance, that's all dependent on your application—you'd need to evaluate that yourself.
