### ISSUE TITLE
Offline data store and sync with server once online

### ISSUE THREAD

**Issue by kirantpatil** [rossta/serviceworker-rails#42]
Hi,

I want to build a app where, if there is no internet connection, app should store data locally. Once internet connection establishes it should sync back to server.

Is it possible to do now using serviceworker-rails ?

Please guide me on how to approach and any pointers  ?

Thanks,
Kiran.

**Comment by ferrettim** [comment]
i'm interested in this as well...i haven't found any info though.

**Comment by ChaseLEngel** [comment]
I have a similar goal. I've found IndexedDB to be very useful for storing data locally. As for service worker I found this resource helpful: https://jakearchibald.com/2014/offline-cookbook/

**Comment by gdurelle** [comment]
Looks more like a StackOverflow than an issue, but here :
https://rossta.net/blog/make-your-rails-app-a-progressive-web-app.html
Also an amzing doc from MDN : https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

**Comment by rossta** [comment]
@kirantpatil This gem provides the glue to help you setup a serviceworker in a typical Rails app that uses the asset pipeline. You could use serviceworker as part of a more complex application like what you've described, but this gem isn't meant to provide that additional functionality.

Thanks @ChaseLEngel and @gdurelle for providing links to additional resources to this question.
