### ISSUE TITLE
Rails 5 404 in Production

### ISSUE THREAD

**Issue by ChaseLEngel** [rossta/serviceworker-rails#44]
I have Service Worker running fine in Development but in Production /serviceworker.js returns 404.

`Error registering Service Worker :TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.`

Nginx error log:
`[error] 29580#29580: *11 open() "/var/www/[APP]/public/serviceworker.js" failed (2: No such file or directory), client: [IP], server: [URL], request: "GET /serviceworker.js HTTP/1.1", host: “[URL]”, referrer: "https://[URL]/serviceworker.js"`

I'm running Rails 5.1.3 and serviceworker-rails 5.5.0. I have serviceworker.rb matching "/serviceworker.js" and compiling serviceworker.js to the public/assets directory.

Any suggestions?

**Comment by rossta** [comment]
Have you tried compiling locally with production settings to troubleshoot? 

What looking about your nginx settings... it looks like the request isn't hitting Rails? Perhaps any file with a `.js` extension is simply proxied to your public directory without proxy passing to your Rails server?

**Comment by ChaseLEngel** [comment]
You were correct, my nginx config wasn't passing /serviceworker.js to Rails. Once I corrected the regex in the nginx config it worked fine. Thanks for the help.

**Comment by rossta** [comment]
Great, glad you got it figured out!

**Comment by victorbucutea** [comment]
Guys I have the same problem. Here is my config:

`Rails.application.configure do
  config.serviceworker.routes.draw do
    match "/sw.js" 
  end
end`


When running in development, everything works fine, if running in production ENV i get this :ActionController::RoutingError (No route matches [GET] "/sw.js")

**Comment by victorbucutea** [comment]
Besides the things above I had to configure  `config.public_file_server.enabled` to true in order to be accessed with localhost:3000/sw.js, which is quite upseting. Isn't there another way ?
