### ISSUE TITLE
Foundation 6 sticky header stops working after service worker installs

### ISSUE THREAD

**Issue by croche2574** [rossta/serviceworker-rails#48]
Not sure if this is a bug in my code, with the serviceworker, or with Foundation, but after the serviceworker installs on the first page load, the sticky top-bar stops working when the page is refreshed.  The only way to fix is to clear the browser's cache, but this fix is only temporary.

**Comment by rossta** [comment]
The installed serviceworker is only meant to be a starting point. You'll need to make it your own edits for it to work with conflicting use cases.

If you're able to point to a reproduction, perhaps the community can help you troubleshoot.
