### ISSUE TITLE
Integration tests pass. Server is a routing error.

### ISSUE THREAD

**Issue by fadec** [rossta/serviceworker-rails#50]
I'm attempting to use 'serviceworker-rails', branch: 'master' with webpack.

I configure the middleware to find my serviceworker pack as follows.

    # config/initializers/serviceworker.rb

    Rails.application.configure do
      config.serviceworker.routes.draw do
        get "/serviceworker.js" => "serviceworker.js", pack: true
      end
    end

And when I run this controller test it passes.

    # test/controllers/notifications_controller_test.rb
    
    require 'test_helper'
    
    class NotificationsControllerTest < ActionDispatch::IntegrationTest
      def test_webpacker_serviceworker
        get "/serviceworker.js"
        assert_response :success
      end
    end

Yet when I `curl http://localhost:3000/serviceworker.js` I get a routing error.

I'm posting here because I get the sames behavior when running the rails sample contained in the gem sources. All of the tests pass, but visiting http://localhost:3000/webpack-serviceworker.js on `rails s` is a routing error. I would expect to see the the wepacked serviceworker.js. I get the same result whether I `rake assets:precompile` or `bin/webpack-dev-server`

I added the following line to config/initializers/serviceworker.rb:

    get "/helpme.js" => "serviceworker.js", pack: true

however visitng '/helpme.js' served up the app/assets/javascripts/serviceworker.js. I expected it instead to serve a packed version of app/javascripts/packs/serviceworker.js. I added a test case and it passed, so this test is also getting the correct routing while `rails s` gets it wrong.

    def test_webpacker_serviceworker2
      if defined?(Webpacker)
        get "/helpme.js"
        assert last_response.ok?
        assert_match(/console.log\(.*'Hello from Webpack ServiceWorker!'.*\);/, last_response.body)
      else
        assert_raises ActionController::RoutingError do
          get "/webpack-serviceworker.js"
        end
      end
    end

Using ruby 2.5.0.

**Comment by fadec** [comment]
I found the problem. Before running `bin/webpack-dev-server` my public/packs/manifest.json looks like this...

```
{
  "application.js": "/packs/application-8ff1445dc98fb466d5e3.js",
  "application.js.map": "/packs/application-8ff1445dc98fb466d5e3.js.map",
  "serviceworker.js": "/packs/serviceworker-a53902923bf1306315fe.js",
  "serviceworker.js.map": "/packs/serviceworker-a53902923bf1306315fe.js.map"
}
```
After running webpack-dev-server it looks like this, tldr different hashes
```
{
  "application.js": "/packs/application-6544c0efa51f5d0ad22c.js",
  "application.js.map": "/packs/application-6544c0efa51f5d0ad22c.js.map",
  "serviceworker.js": "/packs/serviceworker-f07d2fd35a1658c9a4ac.js",
  "serviceworker.js.map": "/packs/serviceworker-f07d2fd35a1658c9a4ac.js.map"
}
```

And it stays like that even when I shutdown webpack-dev-server. So if I run webpack-dev-server once and shut it down, serviceworker-rails is looking for the file with the webpack-dev-server hash. ServiceWorker::Handlers::WebpackerHandler only serves files.

To work around this I can `rm -rf public/packs` every time I shut down webpack-dev-server or do some other thing that forces the manifest to get remade, like change a source file and then refresh the browser.

**Comment by rossta** [comment]
Correct, for this project to work with the webpack-dev-server, the [WebpackHandler](https://github.com/rossta/serviceworker-rails/blob/4ebe4fff21f96775dc3ff62129ec10de4f2cc991/lib/serviceworker/handlers/webpacker_handler.rb#L8) would need to proxy requests [like Webpacker does in development](https://github.com/rails/webpacker/blob/14ac214e091ca6b8861f0c7bd4078b111c2309e4/lib/webpacker/dev_server_proxy.rb#L3) (or delegate to the Webpacker proxy)... it just hasn't been implemented yet. Pull requests are welcome :)
