### ISSUE TITLE
Caching dynamic urls

### ISSUE THREAD

**Issue by mark-kraemer** [rossta/serviceworker-rails#57]
Is it possible to cache a dynamic url? For example I have the url `organizations/4/users/1`. I don't want a cache for each user in each organization. The html is going to be the same for the shell of page, the data will be loaded from index db, and then added to the page via react components. Is there a way to do this in the `cache.addAll` function? Like `organizations/*/users/*`? Or is there another way? Thanks

**Comment by rossta** [comment]
Yes, it's possible. You would have to extend your `serviceworker.js` to handle this url pattern and manage the cache with the appropriate strategy. It could look something like (not tested):

```javascript
// serviceworker.js
self.addEventListener('fetch', function(event) {
  if (event.request.match(/organizations\/.*\/users\/.*/) {
    // implement caching strategy
  }
});
```
For more info on writing custom responses, [check out this article](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Custom_responses_to_requests).

Writing your own custom responses may get cumbersome, at which point, you might consider using a service worker abstraction layer, like [Workbox](https://developers.google.com/web/tools/workbox/).
