### ISSUE TITLE
If this gem is present in Gemfile and installed, an error is thrown at each rails invocation

### ISSUE THREAD

**Issue by gabrieletassoni** [rossta/serviceworker-rails#59]
Ruby on Rails: 5.2.1
serviceworker-rails: 0.5.5

If i comment out the serviceworker-rails gem dependency from Gemfile, it works, with the gem installed (and present in the gemfile), whenever I use the rails command it throws the following error (which looks like a bit meaningful, but something broken with rails 5.2.1 must exist).

`$ rails c
/home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/stack.rb:97:in `push': can't modify frozen Array (RuntimeError)
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/stack.rb:97:in `use'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/serviceworker-rails-0.5.5/lib/serviceworker/engine.rb:23:in `block in <class:Engine>'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/gabrieletassoni/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /home/gabrieletassoni/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/gabrieletassoni/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/gabrieletassoni/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/gabrieletassoni/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /home/gabrieletassoni/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /home/gabrieletassoni/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/gabrieletassoni/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /home/gabrieletassoni/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
	from /home/gabrieletassoni/appdemo/config/environment.rb:5:in `<main>'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /home/gabrieletassoni/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/gabrieletassoni/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/gabrieletassoni/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
`

Thank you very much for the help on figure out this issue.

**Comment by gabrieletassoni** [comment]
Yes, I'm using rails_admin 1.4.1

**Comment by rossta** [comment]
Looks like there's an issue with `1.4.1`. Does downgrading to `1.4.0` as others have described resolve the issue? sferik/rails_admin#3060

**Comment by gabrieletassoni** [comment]
Thank you @rossta I'll try the downgrade the next few days and let you know.

**Comment by gabrieletassoni** [comment]
Hi @rossta ,
indeed downgrading rails_admin proved a suitable workaround, hope a fix will come out soon from rails_admin side.

Thank you for the help, I'm closing this
