### ISSUE TITLE
gem removal

### ISSUE THREAD

**Issue by maxence33** [rossta/serviceworker-rails#61]
I wanted to try `serviceworker-rails` though I realised I am way too unexperienced with Javascript to properly use it. 

But when removing `gem serviceworker-rails` from my gemfile, I started to experience errors such as `Can't resolve image into URL: undefined method 'serviceworker' for #<Rails::Application::Configuration:0x000055859c1142f8>` on random views..

Is there a specific procedure to deactivate service workers after the gem is removed ?

**Comment by rossta** [comment]
You probably need to "unregister" the serviceworker in your browser. If you're using Chrome: Dev Tools > Application > Service Workers > Find the serviceworker in list and click "Unregister"

**Comment by maxence33** [comment]
Thank you. I am actually keeping the gem and will try to dive in it as I am learning JS...
But now I know what was the problem.
