### ISSUE TITLE
Unable to load manifest.json.erb file using suggested link structure 

### ISSUE THREAD

**Issue by tonydehnke** [rossta/serviceworker-rails#70]
* I'm a newbie, so please forgive me if this isn't correct or well structured *

When setting up serviceworker-rails in my Rails app I ran into an issue getting the manifest.json file to load.

Changing the <link> installed during the serviceworker-rails install procedure fixed it.  
So I'm wondering if we should change it in the readme and installer. 
Here is what worked for me:

Old  format from install and Readme file:
`<link rel="manifest" href="/manifest.json" />`

New format that works for me:
`<link href="<%= asset_path ('/manifest.json.erb') %>" rel="manifest" />`

I am running:
ruby 2.6.2
rails 5.2.3
serviceworker-rails 0.5.5

If you have any other questions or suggestions, please feel free to ask or let me know so I can continue to learn and improve.   Thank you.

**Comment by rossta** [comment]
Thanks for the report. Just to clarify, did you add a route matcher in your `app/initializers/serviceworker.rb` file?

```ruby
Rails.application.configure do
  config.serviceworker.routes.draw do
    # ...

    match "/manifest.json"  # <= this line is needed
  end
end
```
