### ISSUE TITLE
Can't link to offline.html

### ISSUE THREAD

**Issue by bsde1234** [rossta/serviceworker-rails#79]
In my rails app I can't link to offline.html at root. I can't link to any file in root folder. It redirects to root of domain Why?

**Comment by bsde1234** [comment]
Edit: But I can access offline.html at `https://www.example.com/public/offline.html`.

**Comment by rossta** [comment]
I'm not sure how to help without more info. I'd be happy to reopen this issue with more info that can be addressed in this project.
