### ISSUE TITLE
Support rails 6

### ISSUE THREAD

**Issue by afurourrego** [rossta/serviceworker-rails#80]
Hi, does serviceworker work in Rails 6? He tried to install and failed to make it work.
I get this message:
![image](https://user-images.githubusercontent.com/20806073/66007818-7b297100-e479-11e9-935f-ef807397bf6a.png)

**Comment by Haguilar91** [comment]
Not working for me either.

**Comment by aseroff** [comment]
I can tell you that it is working for me on rails 6.0.2

It's just JS, after all.

**Comment by Haguilar91** [comment]
I get the no matching service worker detected error, you get ehe same @aseroff ?

**Comment by rossta** [comment]
Please add steps to reproduce the issue.

**Comment by afurourrego** [comment]
It already works correctly.
PWA are somewhat demanding, you must meet certain requirements in the manifest or your Service-Worker will not work.
Here I did a step by step which works correctly in Rails6.
I still have to pass it to English. At the moment it is in Spanish.

https://gist.github.com/afurourrego/666ea6c5a9ae927fe735b4527e195c4d
